fix back end spelling
dotnet/spark pull request #344
Opened 2019-11-20 20:30 UTC by mairaw

I noticed in the docs that back end was misspelled. It's either two words or hyphened when used as an adjective: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/back-end

I've only changed text and comments, but not variable names.

2019-11-20 21:08 UTC, imback82 commented
Can't `backend`,`back-end` and `back end` be used interchangeably? https://en.wikipedia.org/wiki/Back_end

2019-11-21 02:12 UTC, mairaw commented
I pointed to the Microsoft style guide above - that's our official guideline. Also, if you look at the examples under computing in the Wikipedia article, they follow the same rules as I described. But it's up to you whether you wanna take this change or not.

2019-12-06 05:00 UTC, imback82 approved these changes
LGTM

2019-12-06 20:51 UTC, imback82 requested changes

2019-12-06 20:51 UTC, imback82 commented on src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
>          println("***********************************************************************")
Can you update https://github.com/dotnet/spark/blob/master/src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala as well? That's causing the test failures.

2022-03-31 17:25 UTC, mairaw commented
I rolled back some of the changes and kept only the ones in code comments and Markdown.

2026-09-04 18:24 UTC, closed without merging

2026-09-04 18:24 UTC, mairaw commented
Closing this old PR. Doesn't look it will be taken.